// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDftR8FMJqlZqEdsjOcRF491VfvJ-Lmfe4',
    appId: '1:942567714332:web:07cc150689318d0233b9d9',
    messagingSenderId: '942567714332',
    projectId: 'pockettracker-3a93c',
    authDomain: 'pockettracker-3a93c.firebaseapp.com',
    storageBucket: 'pockettracker-3a93c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18QFgjsTSYhQ8fwOlFeZUClBL4HZG0go',
    appId: '1:942567714332:android:49c17136d8cbeb7d33b9d9',
    messagingSenderId: '942567714332',
    projectId: 'pockettracker-3a93c',
    storageBucket: 'pockettracker-3a93c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMCfz3B5yrRiC_M20XfpZIFY83M_d1mS4',
    appId: '1:942567714332:ios:36c3e73456ea17e933b9d9',
    messagingSenderId: '942567714332',
    projectId: 'pockettracker-3a93c',
    storageBucket: 'pockettracker-3a93c.appspot.com',
    iosBundleId: 'com.example.expenseTrackingApp',
  );
}
